name: SpawnDecoration
version: '${project.version}'
main: fr.supermax_8.spawndecoration.SpawnDecorationPlugin
api-version: 1.16
depend: [ModelEngine]
authors: [ SuperMax_8 ]
description: Plugin to add dynamic decoration in your spawn with ModelEngine
website: pyritemc.fr
commands:
  spawndecoration:
    permission: spawndecoration.use